name: bootstrap-datetime
markdown: redcarpet
highlighter: pygments
exclude: ['bower_components', 'build', 'node_modules', 'src']

repo: git@github.com:sandersky/bootstrap-datetime.git

license:
  mit: https://raw.githubusercontent.com/sandersky/bootstrap-datetime/master/LICENSE
  creative_commons: https://raw.githubusercontent.com/sandersky/bootstrap-datetime/master/docs/LICENSE