name: bootstrap-datetime
markdown: redcarpet
highlighter: pygments

repo: git@github.com:sandersky/bootstrap-datetime.git

license:
  mit: https://raw.githubusercontent.com/sandersky/bootstrap-datetime/master/LICENSE
  creative_commons: https://raw.githubusercontent.com/sandersky/bootstrap-datetime/master/docs/LICENSE